function Hd = IIR_Butterworth
%IIR_BUTTERWORTH Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
% Generated on: 05-Jul-2022 00:54:14

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in kHz.
Fs = 122;  % Sampling Frequency

N   = 10;  % Order
Fc1 = 35;  % First Cutoff Frequency
Fc2 = 60;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
